#  Template maven-build

#  This template allows you to test and build your Java project with Maven.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: pom.xml and appropriate project structure should exist in the repository.

image: maven:3.6.3

pipelines:
  default:
    - parallel:
      - step:
          name: maven build 
          caches:
            - maven
          script:
            - mvn clean install
  branches:
   feature/*:
    - step:
        name: Maven Build 
        caches:
          - maven 
        script:
          - echo "This is a festure branch build."
          - mvn clean install 